//! The per-surface artefacts.
//!
//! Two targets exist, because two consumers exist:
//!
//!   - `fields` — the union of `requires.engine_fields`, for the firmware's `enginegen`
//!     to resolve against the selected engine profile. This is the whole of a module's
//!     reach into the dongle: it states a requirement and is told yes or no at build
//!     time, on a workstation. It can never make a car poll a PID.
//!   - `go` — a registry the server compiles in: the module set, its identity, its
//!     derivations, views and named queries, as data.
//!
//! The Nuxt and Swift targets are deliberately absent. A module's `ui/` is meant to be a
//! Nuxt layer and its metrics to become Swift descriptors, but neither has a consumer
//! yet (M4 and M6 of the plan). Generating artefacts nobody reads would be guessing at
//! their shape, and the guess would be committed.

use std::fmt::Write as _;

use crate::manifest::{Module, Sample, Status};

/// The field set, one per line, sorted and deduplicated. A plain list because its reader
/// is a Makefile and then a Rust program in another repository.
pub fn fields(mods: &[&Module]) -> String {
    let mut all: Vec<&str> = mods
        .iter()
        .filter_map(|m| m.manifest.requires.as_ref())
        .flat_map(|r| r.engine_fields.iter().map(String::as_str))
        .collect();
    all.sort_unstable();
    all.dedup();

    let mut out = String::new();
    out.push_str("# GENERATED by modgen. DO NOT EDIT.\n");
    out.push_str("#\n");
    out.push_str(
        "# The capture fields the selected modules require, from engine/v1's acquisition\n",
    );
    out.push_str(
        "# `field` enum. The firmware's enginegen resolves these against the engine profile\n",
    );
    out.push_str("# it is building and fails the build when one is not provided.\n");
    let _ = writeln!(out, "# modules: {}", id_list(mods));
    out.push_str("#\n");
    if all.is_empty() {
        out.push_str("# (none: no selected module requires a capture field)\n");
    }
    for f in all {
        let _ = writeln!(out, "{f}");
    }
    out
}

fn id_list(mods: &[&Module]) -> String {
    mods.iter()
        .map(|m| m.manifest.id.as_str())
        .collect::<Vec<_>>()
        .join(",")
}

fn go_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// A Go source file the server embeds: the module set as data, with its identity.
///
/// Data and not code, because a module never ships executable anything. The server reads
/// these structs, applies the derivations through DuckDB and registers the queries.
pub fn go(mods: &[&Module], identity: &str, package: &str) -> String {
    let mut out = String::new();
    out.push_str("// GENERATED by modgen from a cairn-modules checkout. DO NOT EDIT.\n//\n");
    out.push_str(
        "// The module set as data. A module never ships executable code: a derivation is a\n",
    );
    out.push_str(
        "// SQL expression evaluated by DuckDB, and a query is a parameterised SELECT bound\n",
    );
    out.push_str("// by the server. See contracts/module/v1/spec.md.\n//\n");
    let _ = writeln!(out, "// {identity}");
    let _ = writeln!(out, "\npackage {package}\n");

    out.push_str(
        "// Identity is the module-set identity string. It is folded into the store contract\n",
    );
    out.push_str(
        "// digest and reported in v_reproducibility, so a rebuild under a different module\n",
    );
    out.push_str("// set is visibly a different rebuild rather than a silent mismatch.\n");
    let _ = writeln!(out, "const Identity = {}\n", go_str(identity));

    out.push_str("// Set is the compiled-in module set, in id order.\n");
    out.push_str("var Set = []Module{\n");
    for m in mods {
        let f = &m.manifest;
        let _ = writeln!(out, "\t{{");
        let _ = writeln!(out, "\t\tID:      {},", go_str(&f.id));
        let _ = writeln!(out, "\t\tVersion: {},", f.version);
        let _ = writeln!(out, "\t\tName:    {},", go_str(&f.name));
        let _ = writeln!(out, "\t\tStatus:  {},", go_str(&f.status));
        let _ = writeln!(
            out,
            "\t\tDigest:  {},",
            go_str(&crate::manifest::hex64(&m.sha256))
        );

        if let Some(r) = &f.requires {
            if !r.store.is_empty() {
                let _ = writeln!(out, "\t\tRequiresStore: []string{{");
                for c in &r.store {
                    let _ = writeln!(out, "\t\t\t{},", go_str(c));
                }
                let _ = writeln!(out, "\t\t}},");
            }
            if !r.engine_fields.is_empty() {
                let _ = writeln!(out, "\t\tRequiresEngineFields: []string{{");
                for c in &r.engine_fields {
                    let _ = writeln!(out, "\t\t\t{},", go_str(c));
                }
                let _ = writeln!(out, "\t\t}},");
            }
        }

        if !f.derives.is_empty() {
            let _ = writeln!(out, "\t\tDerives: []Derive{{");
            for d in &f.derives {
                let _ = writeln!(
                    out,
                    "\t\t\t{{Column: {}, Type: {}, Expr: {}}},",
                    go_str(&d.column),
                    go_str(&d.ty),
                    go_str(&d.expr)
                );
            }
            let _ = writeln!(out, "\t\t}},");
        }

        if !f.metrics.is_empty() {
            let _ = writeln!(out, "\t\tMetrics: []Metric{{");
            for mt in &f.metrics {
                let _ = writeln!(out, "\t\t\t{{");
                let _ = writeln!(
                    out,
                    "\t\t\t\tKey: {}, Label: {}, Unit: {},",
                    go_str(&mt.key),
                    go_str(&mt.label),
                    go_str(&mt.unit)
                );
                let _ = writeln!(
                    out,
                    "\t\t\t\tSample: {}, SourceView: {}, SourceColumn: {},",
                    go_str(sample_str(mt.sample)),
                    go_str(&mt.source_view),
                    go_str(&mt.source_column)
                );
                if mt.dashboard_highlight {
                    let _ = writeln!(out, "\t\t\t\tDashboardHighlight: true,");
                }
                let _ = writeln!(out, "\t\t\t}},");
            }
            let _ = writeln!(out, "\t\t}},");
        }

        if let Some(q) = &m.queries {
            let _ = writeln!(out, "\t\tQueries: []Query{{");
            for qq in &q.queries {
                let _ = writeln!(out, "\t\t\t{{");
                let _ = writeln!(out, "\t\t\t\tName: {},", go_str(&qq.name));
                if !qq.params.is_empty() {
                    let _ = writeln!(out, "\t\t\t\tParams: []Param{{");
                    for p in &qq.params {
                        let req = p.required.unwrap_or(true);
                        let _ = writeln!(
                            out,
                            "\t\t\t\t\t{{Name: {}, Type: {}, Required: {}}},",
                            go_str(&p.name),
                            go_str(param_str(p.ty)),
                            req
                        );
                    }
                    let _ = writeln!(out, "\t\t\t\t}},");
                }
                let _ = writeln!(out, "\t\t\t\tSQL: {},", go_str(&qq.sql));
                let _ = writeln!(out, "\t\t\t}},");
            }
            let _ = writeln!(out, "\t\t}},");
        }

        if let Some(ui) = &f.ui {
            let _ = writeln!(
                out,
                "\t\tUI: &UI{{Route: {}, NavLabel: {}, NavGroup: {}, NavOrder: {}, VehicleScope: {}}},",
                go_str(&ui.route),
                go_str(&ui.nav.label),
                go_str(nav_str(ui.nav.group)),
                ui.nav.order,
                go_str(ui.vehicle_scope.as_str())
            );
        }
        let _ = writeln!(out, "\t}},");
    }
    out.push_str("}\n");
    out
}

fn sample_str(s: Sample) -> &'static str {
    s.as_str()
}

fn param_str(p: crate::manifest::ParamType) -> &'static str {
    use crate::manifest::ParamType as P;
    match p {
        P::VehicleId => "vehicle_id",
        P::BootId => "boot_id",
        P::Date => "date",
        P::Int => "int",
        P::Number => "number",
        P::String => "string",
    }
}

fn nav_str(g: crate::manifest::NavGroup) -> &'static str {
    use crate::manifest::NavGroup as G;
    match g {
        G::Everyday => "everyday",
        G::Detail => "detail",
    }
}

/// The one-line summary `list` prints.
pub fn summary(m: &Module) -> String {
    let f = &m.manifest;
    let n_fields = f.requires.as_ref().map_or(0, |r| r.engine_fields.len());
    let n_queries = m.queries.as_ref().map_or(0, |q| q.queries.len());
    let claims = if Status::parse(&f.status) == Some(Status::Stub)
        && f.derives.is_empty()
        && f.metrics.is_empty()
    {
        "declaration only".to_string()
    } else {
        format!(
            "{} metric(s), {} derivation(s), {} field(s), {} query(ies)",
            f.metrics.len(),
            f.derives.len(),
            n_fields,
            n_queries
        )
    };
    format!(
        "{:<16} v{:<4} {:<9} {:<16} {}",
        f.id,
        f.version,
        f.status,
        crate::manifest::hex16(&m.sha256),
        claims
    )
}
